# Generated by Django 3.2.9 on 2022-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='email_listing',
            field=models.JSONField(blank=True, default=dict, verbose_name='Email Listing'),
        ),
    ]
